// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v4.23.4
// source: serializer.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_PB_STATUS_UNKNOWN     Status = 0
	Status_PB_STATUS_SUCCESS     Status = 1
	Status_PB_STATUS_FAIL        Status = 2
	Status_PB_STATUS_BUSY        Status = 3
	Status_PB_STATUS_TIMEOUT     Status = 4
	Status_PB_STATUS_UNSUPPORTED Status = 5
	Status_PB_STATUS_ACK         Status = 6
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "PB_STATUS_UNKNOWN",
		1: "PB_STATUS_SUCCESS",
		2: "PB_STATUS_FAIL",
		3: "PB_STATUS_BUSY",
		4: "PB_STATUS_TIMEOUT",
		5: "PB_STATUS_UNSUPPORTED",
		6: "PB_STATUS_ACK",
	}
	Status_value = map[string]int32{
		"PB_STATUS_UNKNOWN":     0,
		"PB_STATUS_SUCCESS":     1,
		"PB_STATUS_FAIL":        2,
		"PB_STATUS_BUSY":        3,
		"PB_STATUS_TIMEOUT":     4,
		"PB_STATUS_UNSUPPORTED": 5,
		"PB_STATUS_ACK":         6,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_serializer_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_serializer_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_serializer_proto_rawDescGZIP(), []int{0}
}

type MqttCmd int32

const (
	MqttCmd_CN_DEFAULT   MqttCmd = 0
	MqttCmd_CN_PUBLISH   MqttCmd = 1
	MqttCmd_CN_SUBSCRIBE MqttCmd = 2
)

// Enum value maps for MqttCmd.
var (
	MqttCmd_name = map[int32]string{
		0: "CN_DEFAULT",
		1: "CN_PUBLISH",
		2: "CN_SUBSCRIBE",
	}
	MqttCmd_value = map[string]int32{
		"CN_DEFAULT":   0,
		"CN_PUBLISH":   1,
		"CN_SUBSCRIBE": 2,
	}
)

func (x MqttCmd) Enum() *MqttCmd {
	p := new(MqttCmd)
	*p = x
	return p
}

func (x MqttCmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MqttCmd) Descriptor() protoreflect.EnumDescriptor {
	return file_serializer_proto_enumTypes[1].Descriptor()
}

func (MqttCmd) Type() protoreflect.EnumType {
	return &file_serializer_proto_enumTypes[1]
}

func (x MqttCmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MqttCmd.Descriptor instead.
func (MqttCmd) EnumDescriptor() ([]byte, []int) {
	return file_serializer_proto_rawDescGZIP(), []int{1}
}

type MqttChannel int32

const (
	MqttChannel_CMD_DEFAULT MqttChannel = 0
	MqttChannel_BUFFERED    MqttChannel = 1
	MqttChannel_UNBUFFERED  MqttChannel = 2
)

// Enum value maps for MqttChannel.
var (
	MqttChannel_name = map[int32]string{
		0: "CMD_DEFAULT",
		1: "BUFFERED",
		2: "UNBUFFERED",
	}
	MqttChannel_value = map[string]int32{
		"CMD_DEFAULT": 0,
		"BUFFERED":    1,
		"UNBUFFERED":  2,
	}
)

func (x MqttChannel) Enum() *MqttChannel {
	p := new(MqttChannel)
	*p = x
	return p
}

func (x MqttChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MqttChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_serializer_proto_enumTypes[2].Descriptor()
}

func (MqttChannel) Type() protoreflect.EnumType {
	return &file_serializer_proto_enumTypes[2]
}

func (x MqttChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MqttChannel.Descriptor instead.
func (MqttChannel) EnumDescriptor() ([]byte, []int) {
	return file_serializer_proto_rawDescGZIP(), []int{2}
}

type MqttMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Key       string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value     string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MqttMsg) Reset() {
	*x = MqttMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serializer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MqttMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MqttMsg) ProtoMessage() {}

func (x *MqttMsg) ProtoReflect() protoreflect.Message {
	mi := &file_serializer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MqttMsg.ProtoReflect.Descriptor instead.
func (*MqttMsg) Descriptor() ([]byte, []int) {
	return file_serializer_proto_rawDescGZIP(), []int{0}
}

func (x *MqttMsg) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MqttMsg) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MqttMsg) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MqttBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel  MqttChannel `protobuf:"varint,1,opt,name=channel,proto3,enum=MqttChannel" json:"channel,omitempty"`
	Msgbatch []*MqttMsg  `protobuf:"bytes,2,rep,name=msgbatch,proto3" json:"msgbatch,omitempty"`
}

func (x *MqttBatch) Reset() {
	*x = MqttBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serializer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MqttBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MqttBatch) ProtoMessage() {}

func (x *MqttBatch) ProtoReflect() protoreflect.Message {
	mi := &file_serializer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MqttBatch.ProtoReflect.Descriptor instead.
func (*MqttBatch) Descriptor() ([]byte, []int) {
	return file_serializer_proto_rawDescGZIP(), []int{1}
}

func (x *MqttBatch) GetChannel() MqttChannel {
	if x != nil {
		return x.Channel
	}
	return MqttChannel_CMD_DEFAULT
}

func (x *MqttBatch) GetMsgbatch() []*MqttMsg {
	if x != nil {
		return x.Msgbatch
	}
	return nil
}

var File_serializer_proto protoreflect.FileDescriptor

var file_serializer_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x07, 0x4d, 0x71, 0x74, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x59, 0x0a, 0x09, 0x4d, 0x71, 0x74, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x12, 0x26, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0c, 0x2e, 0x4d, 0x71, 0x74, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52,
	0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x24, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x62,
	0x61, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4d, 0x71, 0x74,
	0x74, 0x4d, 0x73, 0x67, 0x52, 0x08, 0x6d, 0x73, 0x67, 0x62, 0x61, 0x74, 0x63, 0x68, 0x2a, 0xa3,
	0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x42, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x15, 0x0a, 0x11, 0x50, 0x42, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x55,
	0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x42, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x50,
	0x42, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x42, 0x55, 0x53, 0x59, 0x10, 0x03, 0x12,
	0x15, 0x0a, 0x11, 0x50, 0x42, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x54, 0x49, 0x4d,
	0x45, 0x4f, 0x55, 0x54, 0x10, 0x04, 0x12, 0x19, 0x0a, 0x15, 0x50, 0x42, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x55, 0x50, 0x50, 0x4f, 0x52, 0x54, 0x45, 0x44, 0x10,
	0x05, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x42, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41,
	0x43, 0x4b, 0x10, 0x06, 0x2a, 0x3b, 0x0a, 0x07, 0x4d, 0x71, 0x74, 0x74, 0x43, 0x6d, 0x64, 0x12,
	0x0e, 0x0a, 0x0a, 0x43, 0x4e, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12,
	0x0e, 0x0a, 0x0a, 0x43, 0x4e, 0x5f, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x53, 0x48, 0x10, 0x01, 0x12,
	0x10, 0x0a, 0x0c, 0x43, 0x4e, 0x5f, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x10,
	0x02, 0x2a, 0x3c, 0x0a, 0x0b, 0x4d, 0x71, 0x74, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4d, 0x44, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10,
	0x00, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x55, 0x46, 0x46, 0x45, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12,
	0x0e, 0x0a, 0x0a, 0x55, 0x4e, 0x42, 0x55, 0x46, 0x46, 0x45, 0x52, 0x45, 0x44, 0x10, 0x02, 0x42,
	0x07, 0x5a, 0x05, 0x2e, 0x3b, 0x69, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_serializer_proto_rawDescOnce sync.Once
	file_serializer_proto_rawDescData = file_serializer_proto_rawDesc
)

func file_serializer_proto_rawDescGZIP() []byte {
	file_serializer_proto_rawDescOnce.Do(func() {
		file_serializer_proto_rawDescData = protoimpl.X.CompressGZIP(file_serializer_proto_rawDescData)
	})
	return file_serializer_proto_rawDescData
}

var file_serializer_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_serializer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_serializer_proto_goTypes = []interface{}{
	(Status)(0),       // 0: Status
	(MqttCmd)(0),      // 1: MqttCmd
	(MqttChannel)(0),  // 2: MqttChannel
	(*MqttMsg)(nil),   // 3: MqttMsg
	(*MqttBatch)(nil), // 4: MqttBatch
}
var file_serializer_proto_depIdxs = []int32{
	2, // 0: MqttBatch.channel:type_name -> MqttChannel
	3, // 1: MqttBatch.msgbatch:type_name -> MqttMsg
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_serializer_proto_init() }
func file_serializer_proto_init() {
	if File_serializer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_serializer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MqttMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serializer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MqttBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_serializer_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_serializer_proto_goTypes,
		DependencyIndexes: file_serializer_proto_depIdxs,
		EnumInfos:         file_serializer_proto_enumTypes,
		MessageInfos:      file_serializer_proto_msgTypes,
	}.Build()
	File_serializer_proto = out.File
	file_serializer_proto_rawDesc = nil
	file_serializer_proto_goTypes = nil
	file_serializer_proto_depIdxs = nil
}
